//! `PWSW` - `PipeWire` Switcher
//!
//! Automatically switches audio sinks based on active windows in Wayland compositors.
//! Uses `PipeWire` native tools (`pw-dump`, `pw-metadata`, `pw-cli`) for audio control.
//!
//! # Features
//! - Automatic sink switching based on window rules
//! - Profile switching for analog/digital outputs on the same card
//! - Status bar integration with `JSON` output
//! - Smart toggle between configured sinks
//! - Multi-compositor support via Wayland protocols (`ext-foreign-toplevel-list-v1`, `wlr-foreign-toplevel`)
//!
//! # Supported Compositors
//! - Sway, Hyprland, Niri, River, Wayfire, labwc, dwl, hikari (via `wlr-foreign-toplevel`)
//!
//! # Unsupported Compositors
//! - GNOME/Mutter, KDE Plasma 6 (no supported window management protocols exposed)

pub mod cli;
pub mod commands;
pub mod compositor;
pub mod config;
pub mod daemon;
pub mod daemon_manager;
pub mod ipc;
pub mod logging;
pub mod notification;
pub mod pipewire;
pub mod state;
pub mod style;

#[cfg(feature = "tui")]
pub mod tui;

// Test-only utilities
#[cfg(test)]
pub mod test_utils;

// Build-time information (generated by build.rs)
// Note: Clippy suppressions kept local to generated code (not centralized in Cargo.toml [lints])
// to maintain clear association with the built crate's generated output
#[allow(clippy::needless_raw_string_hashes)]
#[allow(clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Get the full version string with git commit info
///
/// Returns a version string in the format:
/// - `v0.3.1+abc1234` for clean builds
/// - `v0.3.1+abc1234-dirty` for builds with uncommitted changes
/// - `v0.3.1` if git info is unavailable
#[must_use]
pub fn version_string() -> String {
    let base_version = env!("CARGO_PKG_VERSION");

    if let Some(git_commit) = built_info::GIT_COMMIT_HASH_SHORT {
        let dirty = if built_info::GIT_DIRTY == Some(true) {
            "-dirty"
        } else {
            ""
        };
        format!("v{base_version}+{git_commit}{dirty}")
    } else {
        format!("v{base_version}")
    }
}

/// Format uptime in human-readable form (e.g., "1h 30m", "45s")
#[must_use]
pub fn format_uptime(secs: u64) -> String {
    const SECS_PER_MINUTE: u64 = 60;
    const SECS_PER_HOUR: u64 = 3600;

    if secs < SECS_PER_MINUTE {
        return format!("{secs}s");
    }
    if secs < SECS_PER_HOUR {
        return format!("{mins}m", mins = secs / SECS_PER_MINUTE);
    }
    let hours = secs / SECS_PER_HOUR;
    let mins = (secs % SECS_PER_HOUR) / SECS_PER_MINUTE;
    if mins > 0 {
        format!("{hours}h {mins}m")
    } else {
        format!("{hours}h")
    }
}

// Re-export commonly used types for convenience
pub use cli::Args;
pub use config::Config;
pub use state::State;
