//! `PWSW` - `PipeWire` Switcher
//!
//! Automatically switches audio sinks based on active windows in Wayland compositors.
//! Uses `PipeWire` native tools (`pw-dump`, `pw-metadata`, `pw-cli`) for audio control.
//!
//! # Features
//! - Automatic sink switching based on window rules
//! - Profile switching for analog/digital outputs on the same card
//! - Status bar integration with JSON output
//! - Smart toggle between configured sinks
//! - Multi-compositor support via Wayland protocols (wlr-foreign-toplevel, plasma-window-management)
//!
//! # Supported Compositors
//! - Sway, Hyprland, Niri, River, Wayfire, labwc, dwl, hikari (via wlr-foreign-toplevel)
//! - KDE Plasma/KWin (via plasma-window-management)

pub mod cli;
pub mod commands;
pub mod compositor;
pub mod config;
pub mod daemon;
pub mod ipc;
pub mod notification;
pub mod pipewire;
pub mod state;
pub mod style;

#[cfg(feature = "tui")]
pub mod tui;

// Build-time information (generated by build.rs)
#[allow(clippy::needless_raw_string_hashes)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Get the full version string with git commit info
///
/// Returns a version string in the format:
/// - `v0.3.1+abc1234` for clean builds
/// - `v0.3.1+abc1234-dirty` for builds with uncommitted changes
/// - `v0.3.1` if git info is unavailable
pub fn version_string() -> String {
    let base_version = env!("CARGO_PKG_VERSION");

    if let Some(git_commit) = built_info::GIT_COMMIT_HASH_SHORT {
        let dirty = if built_info::GIT_DIRTY == Some(true) {
            "-dirty"
        } else {
            ""
        };
        format!("v{base_version}+{git_commit}{dirty}")
    } else {
        format!("v{base_version}")
    }
}

// Re-export commonly used types for convenience
pub use cli::Args;
pub use config::Config;
pub use state::State;
